### ISSUE TITLE
Error with inputs

### ISSUE THREAD

**Issue by michiel-van-den-engel** [thiesk/wordlemize#2]
After typing output, the program crashes. 

Output on consolt:
```
Type input to wordle.
first
Type output of wordle. Correct -> c; Wrong -> w; Wrong Position -> p
first
Traceback (most recent call last):
  File "/Users/michielvandenengel/Documents/GitHub/wordlemize/main.py", line 168, in <module>
    p.play()
  File "/Users/michielvandenengel/Documents/GitHub/wordlemize/main.py", line 161, in play
    self.model.input(word, processed)
  File "/Users/michielvandenengel/Documents/GitHub/wordlemize/main.py", line 68, in input
    self.__add_know_letter(letter, feedback[pos], [pos])
IndexError: list index out of rang
```

**Comment by thiesk** [comment]
I'll add a better readme and a filter for the input. This is expected behavior.
